#include "WSDA_croptype.h"
// This table is generated by exporting the CropType table in the WSDA database
// to a text file, replacing tabs with ',' an and making a C/C++ struct out of it.
// Do not otherwise change the codes
#ifdef __cplusplus
namespace    VIC_mcrop {
#endif
WSDA_Crop_type_struct /*120618 WSDA_Crop_type*/ WSDA_crop_type[] =
{  //"OID","CropTypeID","CropType","Notes",PARAMETERS_UNDEFINED}
 {0,  0,"unknown"          ,{PHENOLOGY_UNDEFINED,THERMAL_TIME_UNDEFINED,TRANSPIRATION_UNDEFINED,CANOPY_UNDEFINED,BIOMASS_UNDEFINED,ROOT_UNDEFINED,HARVEST_UNDEFINED,CO2_RESPONSE_UNDEFINED}}
,{1,102,"Blueberry"        ,CROP_PARAMETERS_UNDEFINED}
,{2,103,"Cranberry"        ,CROP_PARAMETERS_UNDEFINED}
,{3,104,"Currant"          ,CROP_PARAMETERS_UNDEFINED}
,{4,106,"Strawberry"       ,CROP_PARAMETERS_UNDEFINED}
,{5,107,"Caneberry"        ,CROP_PARAMETERS_UNDEFINED}
,{6,198,"Berry, Unknown"   ,CROP_PARAMETERS_UNDEFINED}
,{7,201,"Barley"           ,CROP_PARAMETERS_UNDEFINED}
,{8,202,"Buckwheat"        ,CROP_PARAMETERS_UNDEFINED}
,{9,204,"Corn, Field"      ,CROP_PARAMETERS_UNDEFINED}
,{10,205,"Corn, Unknown"   ,CROP_PARAMETERS_UNDEFINED}
,{11,206,"Oat"             ,CROP_PARAMETERS_UNDEFINED}
,{12,207,"Rye"             ,CROP_PARAMETERS_UNDEFINED}
,{13,209,"Triticale"       ,CROP_PARAMETERS_UNDEFINED}
//,{OID,Crop_typeID,"name" ,{{emerge,flower,fill,endveg,snsc,mat},{base,cut,opt,max},{ET_coef,LWPwilt,LWPstress,uptake_max},{initial,maximum,green,total, stops ,reduces,fract_half},{RUE,WUE,slopeWUE,opttemp},{plant,emerge,max_depth,curve,sensitivity},{part,ndxunstressed,transloc},{ratio,baseline,elevated,}}}
,{14,210,"Wheat"           ,{{30    ,330   ,350 ,300   ,350 ,700},{   3, 25, 25, 40},{    1.2,  -2000,    -1200,       10 },{   0.01,    0.9,  0.0,  0.7,-1300.0,-1000.0,       0.5},{3.0,5.0,    -0.5,10.0   },{ 0.08,   0.3,     1.5,0.0001,0.5        },{seed_part,    0.45,     0.3},{  1.2,   330  ,     660,}}}
,{15,211,"Wheat Fallow"          ,CROP_PARAMETERS_UNDEFINED}
,{16,298,"Cereal Grain, Unknown" ,CROP_PARAMETERS_UNDEFINED}
,{17,301,"Christmas Tree"  ,CROP_PARAMETERS_UNDEFINED}
,{18,401,"Douglas Fir"     ,CROP_PARAMETERS_UNDEFINED}
,{19,403,"Poplar, Hybrid"  ,CROP_PARAMETERS_UNDEFINED}
,{20,405,"Yew, Pacific"    ,CROP_PARAMETERS_UNDEFINED}
,{21,501,"Bulb, Allium"    ,CROP_PARAMETERS_UNDEFINED}
,{22,502,"Bulb, Daffodil"  ,CROP_PARAMETERS_UNDEFINED}
,{23,503,"Bulb, Dahlia"    ,CROP_PARAMETERS_UNDEFINED}
,{24,504,"Bulb, Iris"      ,CROP_PARAMETERS_UNDEFINED}
,{25,505,"Bulb, Tulip"     ,CROP_PARAMETERS_UNDEFINED}
,{26,506,"Bulb, Peony"     ,CROP_PARAMETERS_UNDEFINED}
,{27,598,"Bulb, Unknown"   ,CROP_PARAMETERS_UNDEFINED}
,{28,601,"Green Manure"    ,CROP_PARAMETERS_UNDEFINED}
,{29,701,"Alfalfa, Hay"    ,CROP_PARAMETERS_UNDEFINED}
,{30,703,"Alfalfa/Grass, Hay",CROP_PARAMETERS_UNDEFINED}
,{31,708,"Clover, Hay"     ,CROP_PARAMETERS_UNDEFINED}
,{33,713,"Grass, Hay"      ,CROP_PARAMETERS_UNDEFINED}
,{34,720,"Sorghum"         ,CROP_PARAMETERS_UNDEFINED}
,{35,722,"Timothy"         ,CROP_PARAMETERS_UNDEFINED}
,{36,798,"Hay/Silage, Unknown",CROP_PARAMETERS_UNDEFINED}
,{37,801,"Herb, Medicinal" ,CROP_PARAMETERS_UNDEFINED}
,{38,803,"Sage"            ,CROP_PARAMETERS_UNDEFINED}
,{39,804,"Tea"             ,CROP_PARAMETERS_UNDEFINED}
,{40,805,"Parsley"         ,CROP_PARAMETERS_UNDEFINED}
,{41,898,"Herb, Unknown"   ,CROP_PARAMETERS_UNDEFINED}
,{42,901,"Hops"            ,CROP_PARAMETERS_UNDEFINED}
,{43,1001,"Watermelon"     ,CROP_PARAMETERS_UNDEFINED}
,{44,1098,"Melon, Unknown" ,CROP_PARAMETERS_UNDEFINED}
,{45,1101,"Mint"           ,CROP_PARAMETERS_UNDEFINED}
,{47,1202,"Alkali Bee Bed" ,CROP_PARAMETERS_UNDEFINED}
,{48,1203,"CRP"            ,CROP_PARAMETERS_UNDEFINED}
,{50,1205,"Pasture"        ,CROP_PARAMETERS_UNDEFINED}
,{53,1208,"Wildlife Feed"  ,CROP_PARAMETERS_UNDEFINED}
,{54,1303,"Nursery, Silvaculture"   ,CROP_PARAMETERS_UNDEFINED}
,{55,1304,"Nursery, Orchard/Vineyard",CROP_PARAMETERS_UNDEFINED}
,{56,1306,"Nursery, Greenhouse",CROP_PARAMETERS_UNDEFINED}
,{57,1307,"Nursery, Holly",CROP_PARAMETERS_UNDEFINED}
,{58,1308,"Nursery, Lavender",CROP_PARAMETERS_UNDEFINED}
,{59,1309,"Nursery, Lilac",CROP_PARAMETERS_UNDEFINED}
,{60,1311,"Nursery, Ornamental",CROP_PARAMETERS_UNDEFINED}
,{61,1401,"Apple",CROP_PARAMETERS_UNDEFINED}
,{62,1402,"Apricot",CROP_PARAMETERS_UNDEFINED}
,{63,1403,"Cherry"   ,CROP_PARAMETERS_UNDEFINED}
,{64,1404,"Chestnut",CROP_PARAMETERS_UNDEFINED}
,{65,1405,"Filbert",CROP_PARAMETERS_UNDEFINED}
,{66,1407,"Nectarine/Peach",CROP_PARAMETERS_UNDEFINED}
,{67,1409,"Pear",CROP_PARAMETERS_UNDEFINED}
,{68,1410,"Plum",CROP_PARAMETERS_UNDEFINED}
,{69,1411,"Walnut",CROP_PARAMETERS_UNDEFINED}
,{70,1498,"Orchard, Unknown",CROP_PARAMETERS_UNDEFINED}
,{71,1501,"Alfalfa, Seed",CROP_PARAMETERS_UNDEFINED}
,{72,1502,"Beet, Seed",CROP_PARAMETERS_UNDEFINED}
,{73,1503,"Bluegrass, Seed",CROP_PARAMETERS_UNDEFINED}
,{74,1504,"Bromegrass, Seed",CROP_PARAMETERS_UNDEFINED}
,{75,1505,"Brussels Sprouts, Seed",CROP_PARAMETERS_UNDEFINED}
,{76,1506,"Cabbage, Seed",CROP_PARAMETERS_UNDEFINED}
,{77,1507,"Carrot, Seed",CROP_PARAMETERS_UNDEFINED}
,{78,1508,"Clover, Seed",CROP_PARAMETERS_UNDEFINED}
,{79,1509,"Corn, Seed",CROP_PARAMETERS_UNDEFINED}
,{80,1510,"Conifer, Seed",CROP_PARAMETERS_UNDEFINED}
,{81,1511,"Lettuce, Seed",CROP_PARAMETERS_UNDEFINED}
,{82,1512,"Onion, Seed",CROP_PARAMETERS_UNDEFINED}
,{83,1513,"Pea, Seed",CROP_PARAMETERS_UNDEFINED}
,{85,1515,"Potato, Seed",CROP_PARAMETERS_UNDEFINED}
,{86,1516,"Radish, Seed",CROP_PARAMETERS_UNDEFINED}
,{87,1517,"Ryegrass, Seed",CROP_PARAMETERS_UNDEFINED}
,{88,1518,"Safflower, Seed",CROP_PARAMETERS_UNDEFINED}
,{89,1519,"Spinach, Seed",CROP_PARAMETERS_UNDEFINED}
,{90,1520,"Sugar Beet, Seed",CROP_PARAMETERS_UNDEFINED}
,{91,1521,"Swiss Chard, Seed",CROP_PARAMETERS_UNDEFINED}
,{92,1523,"Mustard, Seed",CROP_PARAMETERS_UNDEFINED}
,{94,1526,"Fescue, Seed",CROP_PARAMETERS_UNDEFINED}
,{97,1598,"Seed, Unknown",CROP_PARAMETERS_UNDEFINED}
,{98,1601,"Shellfish",CROP_PARAMETERS_UNDEFINED}
,{99,1698,"Shellfish, Unknown",CROP_PARAMETERS_UNDEFINED}
,{100,1701,"Driving Range",CROP_PARAMETERS_UNDEFINED}
,{101,1702,"Golf Course"   ,CROP_PARAMETERS_UNDEFINED}
,{102,1704,"Sod Farm"      ,CROP_PARAMETERS_UNDEFINED}
,{103,1801,"Artichoke",CROP_PARAMETERS_UNDEFINED}
,{104,1802,"Asparagus",CROP_PARAMETERS_UNDEFINED}
,{105,1803,"Bean, Dry"     ,CROP_PARAMETERS_UNDEFINED}
,{106,1804,"Bean, Green"   ,CROP_PARAMETERS_UNDEFINED}
,{107,1805,"Bean, Lima"    ,CROP_PARAMETERS_UNDEFINED}
,{108,1806,"Beet"          ,CROP_PARAMETERS_UNDEFINED}
,{109,1807,"Broccoli"      ,CROP_PARAMETERS_UNDEFINED}
,{110,1808,"Brussels Sprouts",CROP_PARAMETERS_UNDEFINED}
,{111,1809,"Cabbage",CROP_PARAMETERS_UNDEFINED}
,{112,1810,"Carrot",CROP_PARAMETERS_UNDEFINED}
,{113,1811,"Cauliflower",CROP_PARAMETERS_UNDEFINED}
,{114,1813,"Chickpea"      ,CROP_PARAMETERS_UNDEFINED}
,{115,1814,"Corn, Sweet"   ,CROP_PARAMETERS_UNDEFINED}
,{116,1815,"Cucumber"      ,CROP_PARAMETERS_UNDEFINED}
,{117,1817,"Garlic"        ,CROP_PARAMETERS_UNDEFINED}
,{118,1818,"Leek"          ,CROP_PARAMETERS_UNDEFINED}
,{119,1819,"Lentil"        ,CROP_PARAMETERS_UNDEFINED}
,{120,1820,"Lettuce"       ,CROP_PARAMETERS_UNDEFINED}
,{121,1821,"Market Crops"  ,CROP_PARAMETERS_UNDEFINED}
,{122,1822,"Onion"         ,CROP_PARAMETERS_UNDEFINED}
,{123,1824,"Pea, Dry"      ,CROP_PARAMETERS_UNDEFINED}
,{124,1825,"Pea, Green"    ,CROP_PARAMETERS_UNDEFINED}
,{125,1826,"Pepper",CROP_PARAMETERS_UNDEFINED}
//,{OID,Crop_typeID,"name" ,{{emerge,flower,fill,endveg,snsc,mat },{base,cut,opt,max},{ET_coef,LWPwilt,LWPstress,uptake_max},{initial,maximum,green,total, stops ,reduces,fract_half},{RUE,WUE,slopeWUE,opttemp},{plant?,emerge?,max_depth,curve?,sensitivity},{part,ndxunstressed,transloc},{ratio,baseline,elevated,}}}
//,{126,1827,"Potato"        ,{{160   , 700  , 600,1200  ,1300,2800},{   5, 30, 30, 30},{    1.0,  -1200,     -800,       12 },{   0.01,   0.85, 0.05,  0.8, -600.0, -800.0,       0.5},{ 4.0, 5.0,  -0.5, 10.0  },{ 0.08 ,   0.2 ,      0.6,0.0001, 0.5       },{tuber_part,   0.8 ,     0.3},{  1.2,    330 ,    660}}}
,{126,1827,"Potato"        ,{{130   , 700  , 600,1180  ,1250,2500},{   5, 30, 30, 30},{    1.05,  -1200,     -800,       14 },{   0.01,   0.9, 0.05,  0.8, -600.0, -800.0,       0.5},{ 3.0, 5.4,  -0.5, 10.0  },{ 0.08 ,   0.2 ,      0.6,0.0001, 0.5       },{tuber_part,   0.8 ,     0.3},{  1.2,    380 ,    660}}}
,{127,1828,"Pumpkin",CROP_PARAMETERS_UNDEFINED}
,{128,1829,"Rhubarb",CROP_PARAMETERS_UNDEFINED}
,{129,1830,"Spinach",CROP_PARAMETERS_UNDEFINED}
,{130,1831,"Squash",CROP_PARAMETERS_UNDEFINED}
,{131,1832,"Sugar Beet",CROP_PARAMETERS_UNDEFINED}
,{132,1834,"Tomato",CROP_PARAMETERS_UNDEFINED}
,{133,1839,"Radish",CROP_PARAMETERS_UNDEFINED}
,{134,1898,"Vegetable, Unknown",CROP_PARAMETERS_UNDEFINED}
,{135,1901,"Dill",CROP_PARAMETERS_UNDEFINED}
,{136,1902,"Canola"  ,CROP_PARAMETERS_UNDEFINED}
,{138,1904,"Mustard",CROP_PARAMETERS_UNDEFINED}
,{139,2001,"Grape, Concord",CROP_PARAMETERS_UNDEFINED}
,{140,2002,"Grape, Wine",CROP_PARAMETERS_UNDEFINED}
,{141,2098,"Grape, Unknown",CROP_PARAMETERS_UNDEFINED}
,{142,9701,"Research Station",CROP_PARAMETERS_UNDEFINED}
,{143,9801,"Fallow",CROP_PARAMETERS_UNDEFINED}
,{144,9898,"Unknown"          ,CROP_PARAMETERS_UNDEFINED}
,{145,1530,"Caulflower, Seed" ,CROP_PARAMETERS_UNDEFINED}
,{146,1531,"Sunflower, Seed"  ,CROP_PARAMETERS_UNDEFINED}
,{147,1532,"Yarrow, Seed"     ,CROP_PARAMETERS_UNDEFINED}
,{148,1209,"Developed"        ,CROP_PARAMETERS_UNDEFINED}
,{149,1527,"Grass, Seed"      ,CROP_PARAMETERS_UNDEFINED}
,{151,1840,"Peanut"           ,CROP_PARAMETERS_UNDEFINED}
,{152,721,"Sudangrass"        ,CROP_PARAMETERS_UNDEFINED}
,{153,1533,"Burnett, Seed"    ,CROP_PARAMETERS_UNDEFINED}
,{154,1816,"Kale"             ,CROP_PARAMETERS_UNDEFINED}
,{155,1522,"Bean, Seed"       ,CROP_PARAMETERS_UNDEFINED}
,{156,1525,"Cilantro, Seed"   ,CROP_PARAMETERS_UNDEFINED}
,{157,1312,"Nursery, Caneberry",CROP_PARAMETERS_UNDEFINED}
,{158,1535,"Broccoli, Seed"   ,CROP_PARAMETERS_UNDEFINED}
,{160,1528,"Rutabaga, Seed"   ,CROP_PARAMETERS_UNDEFINED}
,{161,1529,"Turnip, Seed"     ,CROP_PARAMETERS_UNDEFINED}
//,{991,9991,"test1"        ,{{emerge,flower,fill,endveg,snsc,mat},{base,cut,opt,max},{ET_coef,LWPwilt,LWPstress,uptake_max},{initial,maximum,green,total, stops ,reduces,fract_half},{RUE,WUE,slopeWUE,opttemp},{plant,emerge,max_depth,curve,sensitivity},{part,ndxunstressed,transloc},{ratio,elevated,baseline}}}
,{991,9991,"test1"          ,{{30    ,330   ,350 ,300   ,350 ,700},{   3, 25, 25, 40},{    1.2,  -2000,    -1200,       10 },{   0.01,    0.9,  0.0,  0.7,-1300.0,-1000.0,       0.5},{3.0,5.0,    -0.5,10.0   },{ 0.08,   0.3,     1.5,0.0001,0.5        },{seed_part,    0.45,     0.3},{  1.2,   330  ,     660}}}
,{991,9992,"test2"          ,{PHENOLOGY_UNDEFINED,THERMAL_TIME_UNDEFINED,TRANSPIRATION_UNDEFINED,CANOPY_UNDEFINED,BIOMASS_UNDEFINED,ROOT_UNDEFINED,HARVEST_UNDEFINED,CO2_RESPONSE_UNDEFINED}}
,{0,0,0,0,0}
};
//______________________________________________________________________________
//#ifdef __cplusplus
//VIC_crop::
//#endif
Crop_parameters* WSDA_lookup_crop_parameters(nat16 WSDA_code)
{
#ifdef __cplusplus
   VIC_crop::
#endif
   Crop_parameters* params = 0;
   int i;
   for (i = 1; WSDA_crop_type[i].WSDA_code && !params; i++)
   {
      if (WSDA_crop_type[i].WSDA_code == WSDA_code)
         params =  &(WSDA_crop_type[i].parameters);
   }
   return params;
};
//______________________________________________________________________________
#ifdef __cplusplus
};
#endif

